locale: en
title: "Charnwood Eco Hub"
masthead_title: "Charnwood Eco Hub"
separator: "|"
subtitle: "Making Charnwood Greener"
description: ""
copyright: "Charnwood Eco Hub CIC"
logo: assets/img/charnwood-eco-hub.jpg
breadcrumbs: false

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#include:
#  - _pages

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-anchor-headings
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-anchor-headings
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/CharnwoodEcoHub
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: https://twitter.com/CharnwoodEcoHub
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram-square"
      url: https://instagram.com/CharnwoodEcoHub

defaults:
  # _posts
  - scope:
      path: "/workshops-and-events"
      type: workshops-and-events
    values:
      layout: single
      show_overlay_excerpt: false
      show_date: false
      share: true
  - scope:
      path: "/projects"
      type: projects
    values:
      layout: single
      show_overlay_excerpt: false
      show_date: false
      share: true
  - scope:
      path: "/updates"
      type: updates
    values:
      layout: single
      show_overlay_excerpt: false
      show_date: true
      share: true
  - scope:
      path: "/news"
      type: news
    values:
      layout: single
      show_overlay_excerpt: false
      show_date: true
      share: true

collections:
  workshops-and-events:
    output: true
    permalink: /:collection/:title/
  news:
    output: true
    permalink: /:collection/:title/
  updates:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/

#category_archive:
#  type: liquid
#  path: /news/
tag_archive:
  type: liquid
  path: /tags/
